### ISSUE TITLE
NoMethodError at /

### ISSUE THREAD

**Issue by aaronborkovec** [bulletproofnetworks/pigeonhole#38]
Go here:
http://pigeonhole.production.maint.bulletproof.net/

Get error :(

NoMethodError at /
undefined method `length' for nil:NilClass
file: index.haml location: block in singleton class line: 15

![image](https://cloud.githubusercontent.com/assets/11408875/9411469/58486aec-47e3-11e5-9694-25dd1a322c01.png)

**Comment by nerdyness** [comment]
Can't reproduce at the moment but will look into it further.

**Comment by aaronborkovec** [comment]
Checked this about an hour ago (so around midnight AEST) and it was working fine.  Just checked again (1:04 AM) and it's back to showing the "NoMethodError at /" error.

**Comment by jaxxstorm** [comment]
I'm seeing a similar error

```
App 16919 stderr: W, [2015-10-21T16:12:22.651095 #17063]  WARN -- : WARN: tilt autoloading 'tilt/haml' in a non thread-safe way; explicit require 'tilt/haml' suggested.
App 16919 stderr: 2015-10-21 16:12:22 - NoMethodError - undefined method `length' for nil:NilClass:
App 16919 stderr: 	/opt/pigeonhole/app/views/index.haml:15:in `block in singleton class'
App 16919 stderr: 	/opt/pigeonhole/app/views/index.haml:-9:in `instance_eval'
App 16919 stderr: 	/opt/pigeonhole/app/views/index.haml:-9:in `singleton class'
App 16919 stderr: 	/opt/pigeonhole/app/views/index.haml:-11:in `__tilt_70054768502000'
App 16919 stderr: 	/opt/pigeonhole/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `call'
App 16919 stderr: 	/opt/pigeonhole/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:155:in `evaluate'
App 16919 stderr: 	/opt/pigeonhole/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-2.0.1/lib/tilt/haml.rb:17:in `evaluate'
App 16919 stderr: 	/opt/pigeonhole/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
App 16919 stderr: 	/opt/pigeonhole/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:822:in `render'
App 16919 stderr: 	/opt/pigeonhole/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:676:in `haml'
App 16919 stderr: 	/opt/pigeonhole/app/pigeonhole.rb:37:in `block in <top (required)>'
```
